### ISSUE TITLE
Email sent from cozy@localhost instead of cozy@mydomain.tld

### ISSUE THREAD

**Issue by ZeHiro** [SomeAverageDev/cozy-downloader#13]
even if my email is set.
Somethins it wrong here: 
https://github.com/SomeAverageDev/cozy-downloader/blob/master/server/controllers/download.js#L297

Shouldn't is be : 
`user.email || 'cozy@localhost' + '>'`

It results in : 
`Diagnostic-Code: smtp; 504 5.5.2 <cozy@localhost>: Sender address rejected:
    need fully-qualified address`
From my email provider (Gandi)

**Comment by SomeAverageDev** [comment]
that's right, there is a mistake here, I will fix it asap

it should probably be something like 
(user.email || 'cozy@localhost' )+'>'

thanks

**Comment by SomeAverageDev** [comment]
fixed in committed version 0.0.18, @ZeHiro could you try it on your side ?

**Comment by ZeHiro** [comment]
Works fine :+1:
