### ISSUE TITLE
File pointer not freed after deletion

### ISSUE THREAD

**Issue by clochix** [SomeAverageDev/cozy-downloader#16]
When a file is deleted, its file descriptor stay used, so the process doesn't free the disk space.

A user downloaded a huge file that filled up its disk. Deleting the file didn't change anything, he had to restart the application.

**Comment by clochix** [comment]
I think the download of the file may not have ended, so the file descriptor was still in use. Maybe could you find a way to close it if writing on the disk fails or the file has been deleted.

**Comment by SomeAverageDev** [comment]
Hello,
do we have any logs ?

**Comment by clochix** [comment]
Sorry, no logs (the disk was full, so the application was probably unable to log an error).

**Comment by SomeAverageDev** [comment]
@clochix, I think I fixed the issue, but I can't really test it on my dev env. Could you try it for me ?
I updated the code, but did not change the package version for now. I will if you validate the fix
