### ISSUE TITLE
Unable to start version 0.0.16

### ISSUE THREAD

**Issue by clochix** [SomeAverageDev/cozy-downloader#5]
Hi @SomeAverageDev,

You just hit [one of the current limit of Cozy platform](https://github.com/cozy/cozy-controller/issues/101): to start an application, we parse the command defined as the `start script` and use the second word as the main program name.

So, for now, you can only use `node server.js`, not `node --optimize_for_size --max_old_space_size=920 --gc_interval=100 server.js`.

**Comment by SomeAverageDev** [comment]
fixed !
sorry I did not know about this issue

**Comment by clochix** [comment]
Thanks, it works fine now!
