### ISSUE TITLE
Wrong file type

### ISSUE THREAD

**Issue by t1t4nium** [SomeAverageDev/cozy-downloader#7]
When I download a mp3 file from a website ([http://space-music.net/nouveautes/evolution.mp3](http://space-music.net/nouveautes/evolution.mp3)) the file type is wrong (Document) and Cozy Music cannot found him.

When I upload the same file from my computer using the Cozy Files app, the file type is good (Music).

**Comment by SomeAverageDev** [comment]
Hello,
thanks for the issue
I will look into it, probably an option in files to use

**Comment by SomeAverageDev** [comment]
should be fixed
